### PR TITLE
Fix repo URL in setup.py

### PR DESCRIPTION
**Pull request by bartaz**
This was linking to an old inactive URL.

BTW: Needs some adjustments, as I don't know how to make it not fail on line length limit… Split the URL into 2 lines?

### CODE REVIEW

**Comment by carkod** [comment]
Linting is failing
`setup.py:9:80: E[5](https://github.com/canonical-web-and-design/canonicalwebteam.templatefinder/runs/5814390199?check_suite_focus=true#step:4:5)01 line too long (86 > 79 characters)`
You can try putting it into `()` see if you can shorten the characters per line

**Comment by sowasred2012** [comment]
@bartaz could you take another look at this one?

**Comment by bartaz** [comment]
Thanks for fixing the linter. LGTM, but as it's my PR someone else needs to approve on GH.

**Review by mtruj013 — APPROVED** [review]
👍🏻

**Pull request merged**
